# Generated by Django 4.0.6 on 2022-08-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='contenido',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='post',
            name='descripcion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='titulo',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
