# Generated by Django 4.0.6 on 2022-08-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_contenido_alter_post_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contenido',
            field=models.TextField(null=True),
        ),
    ]
