# Generated by Django 4.0.6 on 2022-08-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='activo',
            field=models.BooleanField(default=False),
        ),
    ]
