# Generated by Django 4.0.6 on 2022-08-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_fecha_creacion_alter_post_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
