# Generated by Django 4.0.6 on 2022-08-08 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_post_descripcion_remove_post_fecha_creation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categoria_id',
        ),
        migrations.AddField(
            model_name='post',
            name='categoria_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.categoria'),
        ),
    ]
