# Generated by Django 4.0.6 on 2022-08-31 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_post_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='introduccion',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
