# Generated by Django 4.0.6 on 2022-08-27 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0002_remove_comentarios_mensaje_comentarios_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='domicilio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='telefono',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='comentarios',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
